/**
 * OpenAI Client - Generated by PAL
 *
 * Usage:
 *   import { openai } from './lib/openai-client.js';
 *
 *   const completion = await openai.chat.completions.create({
 *     model: 'gpt-4',
 *     messages: [{ role: 'user', content: 'Hello!' }],
 *   });
 */

import OpenAI from 'openai';

if (!process.env.OPENAI_API_KEY) {
  console.warn('Warning: OPENAI_API_KEY is not set');
}

export const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export default openai;
